### ISSUE TITLE
ImportError: No module named shutil_get_terminal_size

### ISSUE THREAD

**Issue by M-Julius** [brutemap-dev/brutemap#1]
Traceback (most recent call last):
  File "brutemap.py", line 24, in <module>
    from lib.controller.start import initialize
  File "/home/bon007/Hacking/brutemap/lib/controller/start.py", line 8, in <module>
    from lib.controller.target import checkTarget
  File "/home/bon007/Hacking/brutemap/lib/controller/target.py", line 10, in <module>
    from lib.brute.start import bruteForceAttack
  File "/home/bon007/Hacking/brutemap/lib/brute/start.py", line 10, in <module>
    from lib.utils.output import HtmlWriter
  File "/home/bon007/Hacking/brutemap/lib/utils/output.py", line 8, in <module>
    from lib.core import randomHexColor
  File "/home/bon007/Hacking/brutemap/lib/core.py", line 18, in <module>
    from backports.shutil_get_terminal_size import get_terminal_size
ImportError: No module named shutil_get_terminal_size

**Comment by M-Julius** [comment]
Done Solved 

pip uninstall ipython
pip install ipython

**Comment by brutemap-dev** [comment]
this is seen if you have not installed the list of modules needed. For more details see [here](https://github.com/brutemap-dev/brutemap#installation). So I closed this issue (thanks!)
