### ISSUE TITLE
NEED HELP 

### ISSUE THREAD

**Issue by strunz983** [brutemap-dev/brutemap#2]
Hi my OS is Linux kali 4.19.0-kali5-amd64 #1 SMP Debian 4.19.37-2kali1 (2019-05-15) x86_64 GNU/Linux

When i type  python brutemap.py -h
i got this 
Traceback (most recent call last):
  File "brutemap.py", line 24, in <module>
    from lib.controller.start import initialize
  File "/root/stuff/brutemap/lib/controller/start.py", line 8, in <module>
    from lib.controller.target import checkTarget
  File "/root/stuff/brutemap/lib/controller/target.py", line 10, in <module>
    from lib.brute.start import bruteForceAttack
  File "/root/stuff/brutemap/lib/brute/start.py", line 10, in <module>
    from lib.utils.output import HtmlWriter
  File "/root/stuff/brutemap/lib/utils/output.py", line 8, in <module>
    from lib.core import randomHexColor
  File "/root/stuff/brutemap/lib/core.py", line 45, in <module>
    from lib.webdriver import reinitWebDriver
  File "/root/stuff/brutemap/lib/webdriver.py", line 12, in <module>
    from selenium.webdriver import WebKitGTK
ImportError: cannot import name WebKitGTK

python --version is Python 2.7.16
 and
python3 --version is Python 3.7.3rc1 

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by brutemap-dev** [comment]
thanks!. make sure all dependencies have been installed on the python version that the brutemap tool wants and don't forget to install the webdriver for selenium (see here: https://selenium-python.readthedocs.io/installation.html). So I will close this issue, if I am wrong, please open it again!
